#!/usr/bin/env bash
# Installs ComfyUI on macOS for use with the MiniMax H3 *hosted API* nodes.
#
# No weights are downloaded: MinimaxHailuo03* nodes run the generation on
# MiniMax's servers via the Comfy API proxy, so a MacBook only needs to run the
# ComfyUI process itself. (Running H3 locally on Apple Silicon is not possible -
# see ../docs/mac-setup.md for why.)
#
# Usage:
#   ./install.sh [-d ~/ComfyUI] [-r <comfyui git ref>]

set -euo pipefail

INSTALL_DIR="${HOME}/ComfyUI"
# Pinned to a revision that carries the MiniMax H3 API nodes
# (comfy_api_nodes/nodes_minimax.py, MinimaxHailuo03*).
COMFYUI_REF="2eb609766a749e3104485979615e062e401bab97"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${SCRIPT_DIR}")"

while getopts ":d:r:h" opt; do
    case "${opt}" in
        d) INSTALL_DIR="${OPTARG}" ;;
        r) COMFYUI_REF="${OPTARG}" ;;
        h) sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "unknown option -${OPTARG}" >&2; exit 1 ;;
    esac
done

info() { printf '\033[36m[+]\033[0m %s\n' "$1"; }
warn() { printf '\033[33m[!]\033[0m %s\n' "$1"; }
die()  { printf '\033[31m[x]\033[0m %s\n' "$1" >&2; exit 1; }

# --- preflight -------------------------------------------------------------
[[ "$(uname -s)" == "Darwin" ]] || die "This script is for macOS. Use windows/install.ps1 or the RunPod image instead."

ARCH="$(uname -m)"
if [[ "${ARCH}" != "arm64" ]]; then
    warn "Intel Mac detected. The API nodes still work (generation happens server-side), but ComfyUI itself will run on CPU."
fi

command -v git >/dev/null 2>&1 || die "git not found. Install the Xcode command line tools: xcode-select --install"

PY=""
for candidate in python3.13 python3.12 python3; do
    if command -v "${candidate}" >/dev/null 2>&1; then
        ver="$("${candidate}" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
        case "${ver}" in
            3.12|3.13) PY="${candidate}"; break ;;
        esac
    fi
done
[[ -n "${PY}" ]] || die "No Python 3.12/3.13 found. Install one with: brew install python@3.12"
info "Using $(command -v "${PY}") ($("${PY}" --version))"

# --- clone -----------------------------------------------------------------
if [[ -d "${INSTALL_DIR}/.git" ]]; then
    info "ComfyUI already at ${INSTALL_DIR} - fetching"
    git -C "${INSTALL_DIR}" fetch --all --tags
else
    info "Cloning ComfyUI into ${INSTALL_DIR}"
    mkdir -p "$(dirname "${INSTALL_DIR}")"
    git clone https://github.com/comfyanonymous/ComfyUI.git "${INSTALL_DIR}"
fi
git -C "${INSTALL_DIR}" checkout "${COMFYUI_REF}"

[[ -f "${INSTALL_DIR}/comfy_api_nodes/nodes_minimax.py" ]] \
    || die "This ComfyUI revision has no MiniMax API nodes. Pass a newer ref with -r (or 'master')."

# --- venv ------------------------------------------------------------------
VENV="${INSTALL_DIR}/venv"
VPY="${VENV}/bin/python"
if [[ ! -x "${VPY}" ]]; then
    info "Creating venv"
    "${PY}" -m venv "${VENV}"
fi

info "Installing PyTorch (macOS wheels ship with MPS support)"
"${VPY}" -m pip install --upgrade pip setuptools wheel
"${VPY}" -m pip install torch torchvision torchaudio

info "Installing ComfyUI requirements"
if ! "${VPY}" -m pip install -r "${INSTALL_DIR}/requirements.txt"; then
    die "A dependency failed to build. Some ComfyUI extras have no macOS wheel on every
    Python version - the easiest fallback is the official ComfyUI Desktop app
    (https://www.comfy.org/download), which bundles everything. See ../docs/mac-setup.md."
fi

"${VPY}" -c 'import torch; print("torch", torch.__version__, "MPS available:", torch.backends.mps.is_available())'

# --- workflows + launcher --------------------------------------------------
WF_DEST="${INSTALL_DIR}/user/default/workflows/minimax_h3_api"
mkdir -p "${WF_DEST}"
cp "${REPO_ROOT}"/workflows/api/*.json "${WF_DEST}/"
info "API-format workflows copied to ${WF_DEST}"

LAUNCHER="${INSTALL_DIR}/run_comfyui.command"
cat > "${LAUNCHER}" <<'LAUNCH'
#!/usr/bin/env bash
# Generated by install.sh - double-click to start ComfyUI.
cd "$(dirname "$0")"
exec ./venv/bin/python main.py --auto-launch "$@"
LAUNCH
chmod +x "${LAUNCHER}"

cat <<EOF

$(info "Done.")
  Start ComfyUI : ${LAUNCHER}   (double-clickable in Finder)
  Then open     : http://127.0.0.1:8188

Next step - the API nodes bill against a Comfy account, so you have to sign in:
  In the ComfyUI window, open the user menu (top right) and log in.
  Nodes to look for: "MiniMax H3 Text to Video" (category: partner/video/MiniMax).

For headless use, create an API key at https://platform.comfy.org/ and:
  export COMFY_API_KEY=comfyui-xxxxxxxx
  python ${REPO_ROOT}/client/call_local_api.py --prompt "a cat DJing on a rooftop"
EOF
